# Generated by Django 5.1.4 on 2025-01-12 18:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0002_remove_post_category_remove_like_post_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hearts',
            field=models.ManyToManyField(blank=True, related_name='hearted_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
